---
services:
  postgres:
      image: postgres:latest
      container_name: example-database
      environment:
        POSTGRES_DB: example-database
        POSTGRES_USER: example-database
        POSTGRES_PASSWORD: example-database-password
      ports:
        - "5432:5432"
      networks:
        - postgres
      volumes:
        - pg-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
        - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pg-data:

